grade-atk_local:
  when: manual
  timeout: 1 minute
  script:
    - /bin/bash --login isl-grade atk local 
  coverage: '/Score: .*\((\d+)%\)/'

grade-atk_remote:
  when: manual
  timeout: 1 minute 15 seconds
  script:
    - /bin/bash --login isl-grade atk remote 
  coverage: '/Score: .*\((\d+)%\)/'

grade-def1:
  when: manual
  timeout: 50 seconds
  script:
    - /bin/bash --login isl-grade def 1
  coverage: '/Score: .*\((\d+)%\)/'

grade-def2:
  when: manual
  timeout: 50 seconds
  script:
    - /bin/bash --login isl-grade def 2
  coverage: '/Score: .*\((\d+)%\)/'

grade-def3:
  when: manual
  timeout: 50 seconds
  script:
    - /bin/bash --login isl-grade def 3
  coverage: '/Score: .*\((\d+)%\)/'

after_script:
  - /bin/bash grader-cleanup
